project1:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host:
      http_path: 
      schema: default
      threads: 1
      token: 
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host:
      http_path: 
      schema: default
      threads: 1
      token: 
      type: databricks
  target: dev


testProject1:
  outputs:
    dev:
      database:
      - schema
      driver: MySQL ODBC 8.0 ANSI Driver
      password:
      - password
      port:
      - port
      schema:
      - schema
      server:
      - server/host
      type: mysql5
      username:
      - username


    prod:
      database:
      - schema
      driver: MySQL ODBC 8.0 ANSI Driver
      password:
      - password
      port:
      - port
      schema:
      - schema
      server:
      - server/host
      type: mysql5
      username:
      - username
  target: dev
