project1:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-b69aa7e2-7e8a.cloud.databricks.com
      http_path: /sql/1.0/warehouses/fb98aba3a914fa3d
      schema: default
      threads: 1
      token: dapi862ba72c87c742ab21969148942a7185
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host: dbc-b69aa7e2-7e8a.cloud.databricks.com
      http_path: /sql/1.0/warehouses/fb98aba3a914fa3d
      schema: default
      threads: 1
      token: dapi862ba72c87c742ab21969148942a7185
      type: databricks
  target: dev


testProject1:
  outputs:
    dev:
      database:
      - schema
      driver: MySQL ODBC 8.0 ANSI Driver
      password:
      - password
      port:
      - port
      schema:
      - schema
      server:
      - server/host
      type: mysql5
      username:
      - username


    prod:
      database:
      - schema
      driver: MySQL ODBC 8.0 ANSI Driver
      password:
      - password
      port:
      - port
      schema:
      - schema
      server:
      - server/host
      type: mysql5
      username:
      - username
  target: dev
